name: Sync to Hugging Face Spaces

on:
  push:
    branches: [main] # Triggers the workflow every time you push to the 'main' branch

  # Allows you to manually run this workflow from the GitHub Actions tab
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face
        env:          
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        # Replace 'your-username' and 'your-space-name' with your real Hugging Face details        
        run: git push --force https://saminasyd76:$HF_TOKEN@huggingface.co/spaces/saminasyd76/travelwise-agent main